# visit https://github.com/mojombo/jekyll/wiki/Configuration for more settings

paginate: 10 # pagination based on number of posts
paginate_path: "page:num"
exclude: ["README.md"] # files to exclude
highlighter: pygments
markdown: kramdown
disqus: hndr91
google_analytics:

defaults:
  -
    scope:
      path: "" # empty string for all files
    values:
      title: Afif Hendrawan | Sebuah Catatan Samping

description: Sebuah Catatan Samping
author:
  name: M Afif Hendrawan
  email: afif.hendrawan@gmail.com
  github: hndr91
  twitter: @affhendrawan
  linkedin: afifhendrawan
  bio: Technology Enthusiast

rss_path: feed.xml
categories_path: categories.html
tags_path: tags.html

# set it as url of an image
# sidebar_background_image: https://www.dropbox.com/s/g9h23zrycedxtk5/sky.png?raw=1

BASE_PATH:

gems:
  - jekyll-paginate
